import { test, expect } from '@playwright/test'

for (const impl of ['react', 'vue']) {
  test(`${impl} native reset and controlled refusal`, async ({ page }) => {
    await page.goto(`/?case=defaults&impl=${impl}`)
    for (const label of ['Default field', 'Default area']) await page.getByLabel(label, { exact: true }).fill('edited')
    await page.getByLabel('Default checkbox', { exact: true }).uncheck()
    await page.getByLabel('Default switch', { exact: true }).uncheck()
    await page.getByRole('button', { name: 'Reset', exact: true }).click()
    for (const label of ['Default field', 'Default area']) await expect(page.getByLabel(label, { exact: true })).toHaveValue('start')
    await expect(page.getByLabel('Default checkbox', { exact: true })).toBeChecked()
    await expect(page.getByLabel('Default switch', { exact: true })).toBeChecked()
    for (const label of ['Controlled field', 'Controlled area']) { await page.getByLabel(label, { exact: true }).fill('ignored'); await expect(page.getByLabel(label, { exact: true })).toHaveValue('fixed') }
    for (const label of ['Controlled checkbox', 'Controlled switch']) { await page.getByLabel(label, { exact: true }).click(); await expect(page.getByLabel(label, { exact: true })).not.toBeChecked() }
  })
  test(`${impl} notification keyboard navigation and focus restoration`, async ({ page }) => {
    await page.goto(`/?case=notifications&impl=${impl}`)
    const trigger = page.getByRole('button', { name: 'Snackbar', exact: true })
    await trigger.click(); await page.keyboard.press('F6')
    await expect(page.getByRole('region')).toBeFocused()
    await page.keyboard.press('Tab'); await expect(page.getByRole('alertdialog')).toBeFocused()
    await page.waitForTimeout(1700); await expect(page.getByRole('status')).toHaveText('Saved')
    await page.keyboard.press('Tab'); await page.keyboard.press('Enter')
    await expect(page.getByRole('status')).toHaveCount(0)
    await expect(trigger).toBeFocused()
  })
  test(`${impl} form keyboard and values`, async ({ page }) => {
    await page.goto(`/?case=forms&impl=${impl}`)
    await page.getByLabel('Checkbox', { exact: true }).check()
    await page.getByLabel('Switch', { exact: true }).check()
    await page.getByLabel('Beta', { exact: true }).check()
    await page.getByText('Option B', { exact: true }).click()
    await page.getByPlaceholder('Name', { exact: true }).fill('Nexus😀')
    await page.getByLabel('Description', { exact: true }).fill('One\nTwo\nThree\nFour\nFive')
    const state = JSON.parse(await page.getByTestId('state').innerText())
    expect(state).toMatchObject({ checkbox: true, switch: true, radio: 'b', multi: ['a', 'b'], text: 'Nexus😀', area: 'One\nTwo\nThree\nFour\nFive' })
    await expect(page.getByText('6/20', { exact: true })).toBeVisible()
  })
  test(`${impl} dropdown keyboard skips disabled and restores focus`, async ({ page }) => {
    await page.goto(`/?case=selection&impl=${impl}`)
    const trigger = page.getByRole('button', { name: /Choice/ })
    await trigger.click()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('option', { name: 'Beta', exact: true })).toBeFocused()
    await page.keyboard.press('Enter')
    await expect(trigger).toContainText('Beta')
    await expect(trigger).toBeFocused()
    await expect(page.locator('select[name="choice"]')).toHaveValue('b')
    await trigger.click(); await page.keyboard.press('Escape')
    await expect(page.locator('.charcoal-popover')).toHaveCount(0)
  })
  test(`${impl} nested dialog traps and restores focus`, async ({ page }) => {
    await page.goto(`/?case=modal&impl=${impl}`)
    const trigger = page.getByRole('button', { name: 'Open modal', exact: true })
    await trigger.click()
    await page.getByRole('button', { name: 'Nested', exact: true }).click()
    await expect(page.getByText('Nested content', { exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByText('Nested content', { exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Nested', exact: true })).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(page.locator('[role="dialog"]:not([aria-hidden="true"])')).toContainText('Dialog title')
    await page.keyboard.press('Escape')
    await expect(trigger).toBeFocused()
    expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
  })
  test(`${impl} carousel buttons and indicator`, async ({ page }) => {
    await page.goto(`/?case=content&impl=${impl}`)
    const carousel = page.locator('.charcoal-carousel')
    await carousel.hover()
    await carousel.getByRole('button', { name: 'Next', exact: true }).click()
    await expect.poll(() => carousel.locator('.charcoal-carousel__scroller').evaluate(element => element.scrollLeft)).toBeGreaterThan(100)
    if (await page.evaluate(() => CSS.supports('scroll-marker-group', 'after'))) {
      const rect = await carousel.locator('.charcoal-carousel__scroller').boundingBox()
      const count = await carousel.locator('.charcoal-carousel__item').count()
      await page.mouse.click(rect!.x + rect!.width / 2 - (count - 1) * 8, rect!.y + rect!.height + 20)
    } else await carousel.getByRole('button', { name: 'Go to slide 1', exact: true }).click()
    await expect.poll(() => carousel.locator('.charcoal-carousel__scroller').evaluate(element => element.scrollLeft)).toBe(0)
  })
}
test('Astro package SSR and two hydrated Vue islands', async ({ page, request }) => {
  test.skip(!!process.env.ANNEXUS_SKIP_ASTRO)
  const response = await request.get('http://127.0.0.1:4321')
  expect(response.ok()).toBe(true)
  expect(await response.text()).toContain('Server rendered')
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('http://127.0.0.1:4321')
  const first = page.getByRole('region', { name: 'First island' })
  await first.getByRole('button', { name: 'Count 0' }).click()
  await expect(first.getByRole('button', { name: 'Count 1' })).toBeVisible()
  await first.getByLabel('Enable').check()
  await first.getByRole('textbox').fill('Hydrated')
  await expect(first.locator('output')).toHaveText('Hydrated / true')
  await first.getByRole('button', { name: 'Open', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Hydrated')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  const second = page.getByRole('region', { name: 'Second island' })
  await second.scrollIntoViewIfNeeded()
  await second.getByRole('button', { name: 'Count 0' }).click()
  await expect(second.getByRole('button', { name: 'Count 1' })).toBeVisible()
  const ids = await page.locator('[id]').evaluateAll(nodes => nodes.map(node => node.id))
  expect(new Set(ids).size).toBe(ids.length)
  expect(errors).toEqual([])
  expect(await first.getByRole('button', { name: 'Count 1' }).evaluate(node => getComputedStyle(node).borderRadius)).toBe('999999px')
})
